source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

group :development do
  gem "bundler", "~>2.0"
  gem "rake", "~>13.0"
  gem "rspec", "~>3.0"
  gem "webmock", "~>3.0"
  gem "standard"
  gem "simplecov"
  gem "sqlite3"
end

gem "yell", "~>2.0"
gem "prometheus-client"
gem "httparty"
gem "webrick"
gem "thor"

gem "sftp", github: "mlibrary/sftp"
gem "alma_rest_client", github: "mlibrary/alma_rest_client", tag: "v2.0.0"
gem "traject_umich_format", github: "mlibrary/traject_umich_format"

gem "canister"
gem "semantic_logger"
gem "zinzout"

gem "rack" # for sidekiq
gem "traject", "~>3.0", ">=3.8.2"
gem "match_map", "~>3.0"
gem "sequel", "~>5.0"
gem "httpclient", "~>2.0"
gem "library_stdnums", "~>1.0"
gem "sidekiq"
gem "google-apis-sheets_v4"

platforms :jruby do
  gem "naconormalizer"
  gem "jdbc-mysql", "~>8.0"
  gem "psych"
  gem "traject-marc4j_reader", "~> 1.0"
  gem "pry-debugger-jruby"
end

platforms :mri do
  gem "mysql2"
  gem "debug"
end

gem "marc-fastxmlwriter", "~>1.0"

gem "high_level_browse", ">=1.1"

gem "pry"
