[tool.poetry]
name = "search-api"
version = "0.1.0"
description = "API for interacting with solr indexes for Library Search"
authors = [
  "Monique Rio <mrio@umich.edu>", 
  ]
readme = "README.md"
packages = [{include = "api"}]

[tool.ruff]
exclude = [".venv",".vscode",".vscode-server", ".local", ".cache"]

[tool.ruff.lint]
ignore = ["E402"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
fastapi = "^0.135.0"
uvicorn = "^0.34.0"
httpx = "^0.28.1"
pymarc = "^5.2.3"
prometheus-fastapi-instrumentator = "^7.1.0"
pyyaml = "^6.0.3"
opentelemetry-instrumentation-fastapi = "^0.65b0"
opentelemetry-distro = "^0.65b0"
opentelemetry-instrumentation-asyncio = "^0.65b0"
opentelemetry-instrumentation-dbapi = "^0.65b0"
opentelemetry-exporter-otlp = "^1.44.0"
opentelemetry-instrumentation-requests = "^0.65b0"
opentelemetry-instrumentation-httpx = "^0.65b0"
fastapi-structured-logging = "^1.0.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
ruff = "^0.11.2"
responses = "^0.25.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
